### PR TITLE
docs: Adjust flake name, fix casing in README, refactor flake slightly, enable direnv

### PR DESCRIPTION
**Pull request by sshine**

### CODE REVIEW

**Comment by jonringer** [comment]
closing in favor of #31

**Comment by sshine** [comment]
Woohoo, thank you for your awesome work with this book. I look forward to contributing more.

**Comment by jonringer** [comment]
We plan on moving it over to github.com/ekala-project, and using it as the entrypoint for people to learn about nix + packaging + system/NixOS modules

**Comment by sshine** [comment]
I approve very much of this project. Should I keep making pull requests here until the book is moved?

**Comment by jonringer** [comment]
> I approve very much of this project. Should I keep making pull requests here until the book is moved?

Yes, please do so, and even if we archive this, PRs and and commit history will just be moved under a new org

**Pull request closed without merging**
